kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: kopf-elasticsearch
  name: kopf-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kopf-elasticsearch
  template:
    metadata:
      labels:
        k8s-app: kopf-elasticsearch
    spec:
      containers:
      - name: kopf-elasticsearch
        image: lmenezes/cerebro:latest
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: basePath
          value: "/kopf"
        - name: config.basePath
          value: "/kopf"
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kopf-elasticsearch
  name: kopf-elasticsearch
spec:
  ports:
    - port: 30090
      targetPort: 9000
      nodePort: 30090
  type: NodePort
  selector:
    k8s-app: kopf-elasticsearch

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kopf-elasticsearch-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kopf-elasticsearch
          servicePort: 30090