# This binding gives the kube-apiserver user full access to the kubelet API, kubernetes - name of cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-apiserver-kubelet-api-admin
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-api-admin
#  name: system:kubelet-api-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubernetes
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "system:node"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.151"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.152"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.145"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.142"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.141"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.140"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.164"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.153"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.165"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.132"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.131"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.133"
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: "system:node:10.3.3.134"