---
#- name: add Zero-dependency Erlang RPM for RabbitMQ
#  template:
#    src: rabbitmq_erlang.repo.j2
#    dest: /etc/yum.repos.d/rabbitmq_erlang.repo


#- name: Remove old yum cache
#  shell: rm -rf /var/cache/yum/* && yum clean all

#
#- name: Add erlang repositories into the same file (1/2)
#  yum_repository:
#    name: rabbitmq_erlang
#    description: Zero-dependency Erlang RPM for RabbitMQ
#    file: rabbitmq_erlang
#    baseurl: https://packagecloud.io/rabbitmq/erlang/el/7/$basearch
#    gpgcheck: no
#    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
#    sslverify: yes
#
#- name: Add erlang repositories into the same file (2/2)
#  yum_repository:
#    name: rabbitmq_erlang-source
#    description: Zero-dependency Erlang RPM for RabbitMQ
#    file: rabbitmq_erlang
#    baseurl: https://packagecloud.io/rabbitmq/erlang/el/7/SRPMS
#    gpgcheck: no
#    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
#    sslverify: yes
#
#
#- name: yum install erlang
#  yum:
#    name: erlang
#    state: present
#    update_cache: yes


- name: Download Erlang package.
  get_url:
    url: "{{ erlang_rpm_url }}"
    dest: "/tmp/{{ erlang_rpm }}"

- name: Ensure Erlang is installed.
  yum:
    name: "/tmp/{{ erlang_rpm }}"
    state: "present"

