---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: kibana-general
  name: kibana-general-2
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-general
  template:
    metadata:
      labels:
        k8s-app: kibana-general
    spec:
      containers:
      - name: kibana-general
        image: docker.elastic.co/kibana/kibana:7.5.0
        ports:
        - containerPort: 5601
          protocol: TCP
        env:
        - name: SERVER_NAME
          value: "kibana-general.test.internal"
        - name: ELASTICSEARCH_HOSTS
          value: '["http://10.3.3.174:9200","http://10.3.3.175:9200","http://10.3.3.176:9200"]'

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kibana-general
  name: kibana-general
  namespace: monitoring
spec:
  ports:
    - port: 80
      targetPort: 5601
  type: ClusterIP
  selector:
    k8s-app: kibana-general

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-general-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kibana-general.test.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-general
          servicePort: 80