linux_filesystem_map: [ {"dev" : "/dev/sdb", "fstype" : "ext4", "path" : "/var/lib/elasticsearch"} ]

es_cluster_name: "es-devopss-io-cluster"
es_group: "es-devopss-io-group"
es_group_length: "{{ groups['es-devopss-io-group'] | length }}"
es_major_version: "7.x"
es_version: "7.2.0"
jdk_url: "java-jdk/8u202/jdk-8u202-linux-x64.rpm"
es_url: "elasticsearch/{{ es_version }}/elasticsearch-{{ es_version }}-x86_64.rpm"
script_enable: false

# Firewall settings
firewalld_port:
  es-common:
    port: 9200
    protocol: tcp
    state: enabled
    zone: trusted
    permanent: true
  es-transp:
    port: 9300
    protocol: tcp
    state: enabled
    zone: trusted
    permanent: true