---
- name: Add kubescheduler group
  group:
    name: kubescheduler
    state: present

- name: Add kubescheduler user
  user:
    name: kubescheduler
    shell: /bin/bash
    groups: kubescheduler
    append: yes
    state: present

- name: Create a directory if it doesn"t exist
  file:
    path: "/home/kubescheduler"
    state: directory
    mode: 0755
    owner: kubescheduler
    group: kubescheduler

- name: Copy kube-scheduler service file
  template:
    src: kube-scheduler.service.j2
    dest: "/etc/systemd/system/kube-scheduler.service"
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: import handlers tasks
  import_tasks: handlers/main.yml

- name: import goss tests tasks
  import_role:
    name: goss_test
  tags: "k8smaster_goss_tests"