kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: upload-files-devopss-io-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage-class"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi