   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: mailu-roundcube-config
     namespace: devopss-platform-mailserver
   data:
    # DB Connection
    ROUNDCUBE_DB_HOST: "{{ db_host }}"
    ROUNDCUBE_DB_NAME: "roundcube"
    ROUNDCUBE_DB_USER: "{{ db_user }}"
    ROUNDCUBE_DB_PW: "{{ db_password }}"
    FRONT_ADDRESS: "{{ front_k8s_svc_ip }}"
    IMAP_ADDRESS: "{{ imap_k8s_svc_ip }}"