apiVersion: apps/v1
#kind: DaemonSet
kind: Deployment
metadata:
  name: mailu-front
  namespace: devopss-platform-mailserver
  labels:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mail-loadbalancer
      component: ingress-controller
      type: nginx
  template:
    metadata:
      labels:
        k8s-app: mail-loadbalancer
        component: ingress-controller
        type: nginx
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/hostname
#                operator: Exists
#      nodeSelector:
#        kubernetes.io/hostname: "k8sw01.devopss.internal"
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: front
        image: mailu/nginx:{{ mailu_version }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: mailu-config
#        volumeMounts:
#          - name: certs
#            mountPath: /certs
        ports:
          - name: pop3
            containerPort: 110
            hostPort: 110
            protocol: TCP
          - name: pop3s
            containerPort: 995
            hostPort: 995
            protocol: TCP
          - name: imap
            containerPort: 143
            hostPort: 143
            protocol: TCP
          - name: imaps
            containerPort: 993
            hostPort: 993
            protocol: TCP
          - name: smtp
            containerPort: 25
            hostPort: 25
            protocol: TCP
          - name: smtps
            containerPort: 465
            hostPort: 465
            protocol: TCP
          - name: smtpd
            containerPort: 587
            hostPort: 587
            protocol: TCP
          # internal services (not exposed externally)
          - name: smtp-auth
            containerPort: 10025
            protocol: TCP
          - name: imap-auth
            containerPort: 10143
            protocol: TCP
          - name: auth
            containerPort: 8000
            protocol: TCP
          - name: http
            containerPort: 80
            protocol: TCP
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 500Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 30
#      volumes:
#        - name: certs
#          secret:
#            items:
#              - key: tls.crt
#                path: cert.pem
#              - key: tls.key
#                path: key.pem
#            secretName: letsencrypt-certs-allzz
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: devopss-platform-mailserver
  labels:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
spec:
  type: ClusterIP
  clusterIP: "{{ front_k8s_svc_ip }}"
  selector:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
  ports:
  - name: pop3
    port: 110
    protocol: TCP
  - name: pop3s
    port: 995
    protocol: TCP
  - name: imap
    port: 143
    protocol: TCP
  - name: imaps
    port: 993
    protocol: TCP
  - name: smtp
    port: 25
    protocol: TCP
  - name: smtps
    port: 465
    protocol: TCP
  - name: smtpd
    port: 587
    protocol: TCP
  - name: smtp-auth
    port: 10025
    protocol: TCP
  - name: imap-auth
    port: 10143
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP


---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mailu-ingress
  namespace: devopss-platform-mailserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/client-max-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 10m
    nginx.ingress.kubernetes.io/proxy-next-upstream: http_504
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: 180s
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/proxy-connect-timeout: 12s
    nginx.org/proxy-read-timeout: 180s
    nginx.org/proxy-send-timeout: 180s
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  rules:
  - host: "{{ mailu_hostname }}"
    http:
      paths:
      - path: "/admin"
        backend:
          serviceName: front-service
          servicePort: 80
      - path: "/webmail"
        backend:
          serviceName: front-service
          servicePort: 80
      - path: "/webdav"
        backend:
          serviceName: front-service
          servicePort: 80
      - path: "/admin/antispam"
        backend:
          serviceName: front-service
          servicePort: 80
      - path: "/internal"
        backend:
          serviceName: front-service
          servicePort: 80
      - path: "/"
        backend:
          serviceName: front-service
          servicePort: 80
