#apiVersion: apps/v1
#kind: Ingress
#metadata:
#  name: mailu-ingress
#  namespace: devopss-platform-mailserver
#  annotations:
#    kubernetes.io/tls-acme: "true"
#    certmanager.k8s.io/cluster-issuer: letsencrypt-stage
#  labels:
#    app: mailu
#    role: mail
#    tier: backend
#spec:
#  tls:
#  - hosts:
#    - "mail.example.com"
#    secretName: letsencrypt-certs-all # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
#  rules:
#  - host: "mail.example.com"
#    http:
#      paths:
#      - path: "/"
#        backend:
#          serviceName: front
#          servicePort: 80
