---
apiVersion: v1
kind: Service
metadata:
  name: pop3-service
  namespace: devopss-platform-mailserver
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  type: NodePort
  selector:
    app: mailu-imap
    role: mail
    tier: backend
  ports:
  - name: pop3
    port: 110
    targetPort: 110
    nodePort: {{ pop3_node_port }}
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: pop3s-service
  namespace: devopss-platform-mailserver
  labels:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
spec:
  type: NodePort
  selector:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
  ports:
  - name: pop3
    port: 995
    targetPort: 995
    nodePort: {{ pop3s_node_port }}
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: imap-service
  namespace: devopss-platform-mailserver
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  type: NodePort
  selector:
    app: mailu-imap
    role: mail
    tier: backend
  ports:
  - name: pop3
    port: 143
    targetPort: 143
    nodePort: {{ imap_node_port }}
    protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: imaps-service
  namespace: devopss-platform-mailserver
  labels:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
spec:
  type: NodePort
  selector:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
  ports:
  - name: pop3
    port: 993
    targetPort: 993
    nodePort: {{ imaps_node_port }}
    protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: smtp-all-service
  namespace: devopss-platform-mailserver
  labels:
    app: mailu-smtp
    role: mail
    tier: backend
spec:
  type: NodePort
  selector:
    app: mailu-smtp
    role: mail
    tier: backend
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    nodePort: {{ smtp_node_port }}
    protocol: TCP
  - name: smtp-ssl
    port: 465
    targetPort: 465
    nodePort: {{ smtps_node_port }}
    protocol: TCP
#  - name: smtp-starttls
#    port: 587
#    targetPort: 587
#    nodePort: {{ smtpd_node_port }}
#    protocol: TCP



---
apiVersion: v1
kind: Service
metadata:
  name: smtpd--service
  namespace: devopss-platform-mailserver
  labels:
    app: mailu-smtp
    role: mail
    tier: backend
spec:
  type: NodePort
  selector:
    app: mailu-smtp
    role: mail
    tier: backend
  ports:
  - name: smtp-starttls
    port: 587
    targetPort: 587
    nodePort: {{ smtpd_node_port }}
    protocol: TCP
