#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: mail-storage
#  namespace: devopss-platform-mailserver
#
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage-class"
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 30Gi