---
pg_backup_version: "01"
pg_data_backup_dir: "/data/backup"
pg_intermidiate_host_data: "10.3.3.173"
ansible_python_interpreter: "/usr/bin/python3"
# Accounts Database Variables
pg_database_from: "globaldb"
pg_ssh_user_from: "ddumbraveanu"
pg_ssh_password_from: "lSyceu42Y35"
pg_accounts_host_from: "10.1.1.193"
pg_accounts_login_user_from: "postgres"
pg_accounts_login_password_from: "Global10xX"
pg_dir_target_from: "/var/lib/postgres-data/backup"
pg_owner_from: "postgres"
pg_database_to: "globaldb"
pg_accounts_host_to: "10.3.3.172"
pg_accounts_login_user_to: "devopss_su_admin"
pg_accounts_login_password_to: "iiyoxdYzei8Exef98CfE9EiC0"
pg_owner_to: "postgres"
pg_dir_target_to: "/var/lib/pgsql/backup"
#### Shareds DBs #####
pg_shareddbs_host_from: "pgsql11-test-prod-com01.devopss.net"
pg_shareddbs_login_user_from: "postgres"
pg_shareddbs_login_password_from: "Jlz8ZIlBD2w"
pg_shareddbs_host_to: "pgsql12-com-01.test.internal"
pg_shareddbs_login_user_to: "devopss_su_admin"
pg_shareddbs_login_password_to: "iiyoxdYzei8Exef98CfE9EiC0"

# Adtional packages variables
pgsql_major_version: "12"
pgsql_version: "{{ pgsql_major_version }}.0-1PGDG"
pgsql_libs_rpm: "postgresql{{ pgsql_major_version }}-libs-{{ pgsql_version }}.rhel{{ ansible_distribution_major_version }}.x86_64.rpm"
pgsql_libs_rpm_url: "http://{{ devopss_nexus_user_repo }}@{{ devopss_internal_nexus_address_name }}:{{devopss_nexus_port}}/repository/raw-repository/postgresql/{{ pgsql_major_version }}/redhat/{{pgsql_libs_rpm}}"
pgsql_rpm: "postgresql{{ pgsql_major_version }}-{{ pgsql_version }}.rhel{{ ansible_distribution_major_version }}.x86_64.rpm"
pgsql_rpm_url: "http://{{ devopss_nexus_user_repo }}@{{ devopss_internal_nexus_address_name }}:{{devopss_nexus_port}}/repository/raw-repository/postgresql/{{ pgsql_major_version }}/redhat/{{pgsql_rpm}}"
pgsql_contrib_rpm: "postgresql{{ pgsql_major_version }}-contrib-{{ pgsql_version }}.rhel{{ ansible_distribution_major_version }}.x86_64.rpm"
pgsql_contrib_url: "http://{{ devopss_nexus_user_repo }}@{{ devopss_internal_nexus_address_name }}:{{devopss_nexus_port}}/repository/raw-repository/postgresql/{{ pgsql_major_version }}/redhat/{{pgsql_contrib_rpm}}"
python_rpm: "python2-psycopg2-2.8.3-3.rhel7.x86_64.rpm"
python_rpm_url: "http://{{ devopss_nexus_user_repo }}@{{ devopss_internal_nexus_address_name }}:{{devopss_nexus_port}}/repository/raw-repository/postgresql/{{ pgsql_major_version }}/redhat/{{python_rpm}}"

