---
rabbitmq_daemon: rabbitmq-server
rabbitmq_state: started
rabbitmq_enabled: true

#rabbitmq_version: "3.8.0"
#erlang_version: "21.3.8.9"

rabbitmq_rpm: "rabbitmq-server-{{ rabbitmq_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
rabbitmq_rpm_url: "http://{{ devopss_nexus_user_repo }}@{{ devopss_internal_nexus_address_name }}:{{devopss_nexus_port}}/repository/raw-repository/rabbitmq/{{ rabbitmq_version }}/{{rabbitmq_rpm}}"

erlang_rpm: "erlang-{{ erlang_version }}-1.el{{ ansible_distribution_major_version }}.x86_64.rpm"
erlang_rpm_url: "http://{{ devopss_nexus_user_repo }}@{{ devopss_internal_nexus_address_name }}:{{devopss_nexus_port}}/repository/raw-repository/rabbitmq-erlang/{{ erlang_version }}/{{erlang_rpm}}"

goss_test_files: ["rabbitmq.yml"]
monit_rules_files: ["rabbitmq.monit"]