---
# Check if Kafka is installed
- name: Check if Kafka is installed
  stat:
    path: "{{ kafka_install_dir }}"
  register: dir

# add kafka group
- group:
    name: kafka
    state: present
  when: dir.stat.exists == False

# Add kafka user
- user:
    name: kafka
    shell: /bin/bash
    groups: kafka
    append: yes
    state: present
  when: dir.stat.exists == False

# create a directory if it doesn"t exist
- file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: kafka
    group: kafka
  with_items:
     - "/home/kafka"
     - "{{ kafka_install_dir }}"
     - "{{ kafka_log_dir }}"
  when: dir.stat.exists == False

# Unpack Apache Kafka
- name: Unpack Apache Kafka
  unarchive:
    src: "{{ kafka_download_url }}"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    extra_opts: '--strip-components=1'
    owner: kafka
    group : kafka
    mode: "0755"
  when: dir.stat.exists == False
